version: "3"

services:
  app_cand_lata:
    image: jailsonsilva/bg_app:0.1
    ports:
      - 80:80
    stdin_open: true
    tty: true
    networks:
      - frontend
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  frontend: